### ISSUE TITLE
What are the timelines for this project? 

### ISSUE THREAD

**Issue by rafialikhan** [billh93/babel#1]
Sounds exciting to be part of a decentralized e-commerce project. What are the timelines? Are you going to publish this soon? I dont see any activity for the past 2 months.

**Comment by billh93** [comment]
Hey @rafialikhan there is no set timeline. It's just a concept but it's open source so if you would to pursue the project you can. If there is any updates It'll show up on the repository but as of right now it's just a concept at it's best.
